CBA_MiscItem compatibility
ImperialAlex/XLA_FixedArsenal pull request #35
Opened 2017-10-27 15:06 UTC by TheNiner

## Aim of the pull request
This PR fixes the incompatibility of CBA_MiscItems with XLA_FixedArsenal (Reported in #34).

## Description of the problem
Before ACE and ACRE started using CBA_MiscItem, they used the Vanilla Minedetector as the [Base Class](https://github.com/acemod/ACE3/commit/30a8d2db7bc2920524f4ee04e5ba8a250559de8d#diff-7e318c81f1eaa970131e8c19cbf108c8L3), therefore all the Items showed up in the "Misc"-Tab of the Arsenal. The problem is, the new "CBA_MiscItem", which is used in the new version of ACE and ACRE as the Base Class, is [defined as a Bipod](https://github.com/CBATeam/CBA_A3/pull/744/files#diff-7e318c81f1eaa970131e8c19cbf108c8R5). For this reason `BIS_fnc_itemType` returns `["Item","AccessoryBipod"]` in [Line 807 of fn_arsenal](https://github.com/ImperialAlex/XLA_FixedArsenal/blob/master/addons/XLA_FixedArsenal/functions/Inventory/fn_arsenal.sqf#L807). This causes that `_weaponTypeID` [remains at -1](https://github.com/ImperialAlex/XLA_FixedArsenal/blob/master/addons/XLA_FixedArsenal/functions/Inventory/fn_arsenal.sqf#L814) for CBA_MiscItems, since `AccessoryBipod` is not present in the  [`INITTYPES` Macro](https://github.com/ImperialAlex/XLA_FixedArsenal/blob/master/addons/XLA_FixedArsenal/functions/Inventory/fn_arsenal.sqf#L109). As a result, the Items aren't showing up in the Arsenal Misc Tab.

## Description of the fix
We can simply check if the Item has `CBA_MiscItem` as parent and then set the `_weaponTypeSpecific ` to `MineDetector`. The `_weaponTypeID` will then be set to the correct index of the Misc Tab.

2017-10-31 06:04 UTC, shol9570 requested changes
I think this can fix the problem, too!

2017-10-31 06:08 UTC, shol9570 commented
or you can add "AccessoryBipod" type to _types like :
#define INITTYPES\
		_types = [];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_UNIFORM,["Uniform"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_VEST,["Vest"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_BACKPACK,["Backpack"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_HEADGEAR,["Headgear"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_GOGGLES,["Glasses"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_NVGS,["NVGoggles"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_BINOCULARS,["Binocular","LaserDesignator"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_PRIMARYWEAPON,["AssaultRifle","MachineGun","SniperRifle","Shotgun","Rifle","SubmachineGun"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_SECONDARYWEAPON,["Launcher","MissileLauncher","RocketLauncher"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_HANDGUN,["Handgun"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_MAP,["Map"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_GPS,["GPS","UAVTerminal"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_RADIO,["Radio"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_COMPASS,["Compass"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_WATCH,["Watch"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_FACE,[]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_VOICE,[]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_INSIGNIA,[]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_ITEMOPTIC,[]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_ITEMACC,[]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_ITEMMUZZLE,[]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_ITEMBIPOD,["AccessoryBipod"]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_CARGOMAG,[]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_CARGOTHROW,[/*"Grenade","SmokeShell"*/]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_CARGOPUT,[/*"Mine","MineBounding","MineDirectional"*/]];\
		_types set [IDC_RSCDISPLAYFIXEDARSENAL_TAB_CARGOMISC,["FirstAidKit","Medikit","MineDetector","Toolkit"]];

2017-10-31 11:27 UTC, TheNiner commented
The problem with this solution is, that all of the items will show up in the "BIPOD"-Tab of the Arsenal and not in the "Misc"-Tab, where items like the MineDetector are placed.

2017-11-01 07:36 UTC, shol9570 commented
or how about writing in "IDC_RSCDISPLAYFIXEDARSENAL_TAB_CARGOMISC"?

2017-11-01 08:38 UTC, shol9570 commented
Oh I tested it and found all biopod in misc tab.
My suggestion is wrong.
I don't like the code that too much if in it.
But this time, it has no choice i think.

2017-11-03 08:08 UTC, ImperialAlex commented
Sorry guys, my emails for this account got lost so I didn't see this in time! Thanks for fixing this isuse! Open Source FTW!

I'm accepting the PR now, but I won't get around to digging out *.bikey's, setting up a toolchain, etc until tomorrow or sunday

2017-11-03 08:08 UTC, merged